version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    container_name: KeycloakGruasUCAB
    ports:
      - "8180:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=1234
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/keycloak-config.json
    command: start-dev