global using API_GruasUCAB.Department.Application.Queries.GetDepartmentByName;
global using API_GruasUCAB.Department.Application.Queries.GetDepartmentById;
global using API_GruasUCAB.Department.Application.Queries.GetAllDepartments;