// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infraestructure.Database;

#nullable disable

namespace proyectods.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cedula_cliente")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre_completo_cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tlf_proveedor")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("backend.Domain.Entities.Conductor", b =>
                {
                    b.Property<Guid>("Id_conductor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cedula_conductor")
                        .HasColumnType("integer");

                    b.Property<int>("Certificado_medico")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_expira_cedula")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_expira_certificado_medico")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_expira_licencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_nac_conductor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre_completo_conductor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tlf_conductor")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.Property<int>("licencia_conductor")
                        .HasColumnType("integer");

                    b.Property<int>("tipoLicencia")
                        .HasColumnType("integer");

                    b.HasKey("Id_conductor");

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("backend.Domain.Entities.Departamento", b =>
                {
                    b.Property<Guid>("Id_departamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<string>("Descrip_departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre_departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_departamento");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("backend.Domain.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id_estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<string>("Descrip_estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre_estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_estado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("backend.Domain.Entities.Estado_Orden", b =>
                {
                    b.Property<Guid>("Id_estado_incidente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_orden_de_servicio")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_estado")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_fin_incidente")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_inicio_incidente")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_estado_incidente", "Id_orden_de_servicio", "Id_estado");

                    b.HasIndex("Id_estado");

                    b.HasIndex("Id_orden_de_servicio");

                    b.ToTable("Estado_Ordenes");
                });

            modelBuilder.Entity("backend.Domain.Entities.Lugar", b =>
                {
                    b.Property<Guid>("Id_lugar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LugarPadreId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre_lugar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoLugar")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_lugar");

                    b.HasIndex("LugarPadreId");

                    b.ToTable("Lugares");
                });

            modelBuilder.Entity("backend.Domain.Entities.Orden_De_Servicio", b =>
                {
                    b.Property<Guid>("Id_orden_de_servicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Costo_incidente")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<string>("Descrip_incidente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descrip_vehiculo_cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Distancia_incidente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_cliente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_lugar")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_poliza")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_poliza_cliente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_proveedor")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_trabajador")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_vehiculo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_vehiculo_proveedor")
                        .HasColumnType("uuid");

                    b.Property<string>("Ubi_fin_incidente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubi_incidente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubi_inicial_conductor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_orden_de_servicio");

                    b.HasIndex("Id_lugar");

                    b.HasIndex("Id_trabajador");

                    b.HasIndex("Id_poliza_cliente", "Id_poliza", "Id_cliente");

                    b.HasIndex("Id_vehiculo_proveedor", "Id_vehiculo", "Id_proveedor");

                    b.ToTable("Orden_De_Servicios");
                });

            modelBuilder.Entity("backend.Domain.Entities.Poliza", b =>
                {
                    b.Property<Guid>("Id_poliza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<int>("Km_cobertura_poliza")
                        .HasColumnType("integer");

                    b.Property<int>("Monto_base_poliza")
                        .HasColumnType("integer");

                    b.Property<int>("Monto_cobertura_poliza")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre_poliza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Num_poliza")
                        .HasColumnType("integer");

                    b.Property<int>("Precio_km_poliza")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_poliza");

                    b.ToTable("Polizas");
                });

            modelBuilder.Entity("backend.Domain.Entities.Poliza_Cliente", b =>
                {
                    b.Property<Guid>("Id_poliza_cliente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_cliente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_poliza")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_emision_poliza")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_expira_poliza")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_poliza_cliente", "Id_cliente", "Id_poliza");

                    b.HasIndex("Id_cliente");

                    b.HasIndex("Id_poliza");

                    b.ToTable("Poliza_Clientes");
                });

            modelBuilder.Entity("backend.Domain.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id_proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<string>("Denom_comercial_proveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre_proveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rif_proveedor")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_proveedor");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("backend.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<string>("Descrip_rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre_rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("backend.Domain.Entities.Servicio", b =>
                {
                    b.Property<Guid>("Id_servicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Costo_servicio")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<string>("Descrip_servicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre_servicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_servicio");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("backend.Domain.Entities.Servicio_Orden", b =>
                {
                    b.Property<Guid>("Id_servicio_orden")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_servicio")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_orden_de_servicio")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_servicio_orden", "Id_servicio", "Id_orden_de_servicio");

                    b.HasIndex("Id_orden_de_servicio");

                    b.HasIndex("Id_servicio");

                    b.ToTable("Servicio_Ordenes");
                });

            modelBuilder.Entity("backend.Domain.Entities.Telefono", b =>
                {
                    b.Property<Guid>("Id_tlf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Id_cliente")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Id_conductor")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Id_trabajador")
                        .HasColumnType("uuid");

                    b.Property<string>("Num_tlf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_tlf");

                    b.HasIndex("Id_cliente");

                    b.HasIndex("Id_conductor");

                    b.HasIndex("Id_trabajador");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("backend.Domain.Entities.Tipo_Vehiculo", b =>
                {
                    b.Property<Guid>("Id_tipo_vehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<string>("Descrip_tipo_vehiculo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre_tipo_vehiculo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_tipo_vehiculo");

                    b.ToTable("Tipo_Vehiculos");
                });

            modelBuilder.Entity("backend.Domain.Entities.Trabajador", b =>
                {
                    b.Property<Guid>("Id_trabajador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo_de_trabajo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Cedula_trabajador")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre_completo_trabajador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tlf_trabajador")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_trabajador");

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("backend.Domain.Entities.Trabajador_Departamento", b =>
                {
                    b.Property<Guid>("Id_trabajador")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_departamento")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_trabajador", "Id_departamento");

                    b.HasIndex("Id_departamento");

                    b.ToTable("Trabajador_Departamentos");
                });

            modelBuilder.Entity("backend.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Contrasena_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("Correo_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Id_conductor")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Id_proveedor")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Id_trabajador")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_usuario");

                    b.HasIndex("Id_conductor")
                        .IsUnique();

                    b.HasIndex("Id_proveedor")
                        .IsUnique();

                    b.HasIndex("Id_trabajador")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("backend.Domain.Entities.Usuario_Rol", b =>
                {
                    b.Property<Guid>("Id_usuario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_rol")
                        .HasColumnType("uuid");

                    b.HasKey("Id_usuario", "Id_rol");

                    b.HasIndex("Id_rol");

                    b.ToTable("Usuario_Roles");
                });

            modelBuilder.Entity("backend.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<Guid>("Id_vehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Carnet_circulacion")
                        .HasColumnType("boolean");

                    b.Property<string>("Color_vehiculo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_tipo_vehiculo")
                        .HasColumnType("uuid");

                    b.Property<string>("Marca_vehiculo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo_vehiculo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_vehiculo");

                    b.HasIndex("Id_tipo_vehiculo");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("backend.Domain.Entities.Vehiculo_Proveedor", b =>
                {
                    b.Property<Guid>("Id_vehiculo_proveedor")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_proveedor")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_vehiculo")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy_base")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_expira_respon_civil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id_base")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id_conductor")
                        .HasColumnType("uuid");

                    b.Property<bool>("Respon_civil")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt_base")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy_base")
                        .HasColumnType("text");

                    b.HasKey("Id_vehiculo_proveedor", "Id_proveedor", "Id_vehiculo");

                    b.HasIndex("Id_conductor");

                    b.HasIndex("Id_proveedor");

                    b.HasIndex("Id_vehiculo");

                    b.ToTable("Vehiculo_Proveedores");
                });

            modelBuilder.Entity("backend.Domain.Entities.Estado_Orden", b =>
                {
                    b.HasOne("backend.Domain.Entities.Estado", "Estado")
                        .WithMany("Estado_Ordenes")
                        .HasForeignKey("Id_estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Orden_De_Servicio", "Orden_De_Servicio")
                        .WithMany("Estado_Ordenes")
                        .HasForeignKey("Id_orden_de_servicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Orden_De_Servicio");
                });

            modelBuilder.Entity("backend.Domain.Entities.Lugar", b =>
                {
                    b.HasOne("backend.Domain.Entities.Lugar", "LugarPadre")
                        .WithMany("LugaresHijos")
                        .HasForeignKey("LugarPadreId");

                    b.Navigation("LugarPadre");
                });

            modelBuilder.Entity("backend.Domain.Entities.Orden_De_Servicio", b =>
                {
                    b.HasOne("backend.Domain.Entities.Lugar", "Lugar")
                        .WithMany("Orden_De_Servicios")
                        .HasForeignKey("Id_lugar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Trabajador", "Trabajador")
                        .WithMany("Orden_De_Servicios")
                        .HasForeignKey("Id_trabajador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Poliza_Cliente", "Poliza_Cliente")
                        .WithMany("Orden_De_Servicios")
                        .HasForeignKey("Id_poliza_cliente", "Id_poliza", "Id_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Vehiculo_Proveedor", "Vehiculo_Proveedor")
                        .WithMany("Orden_De_Servicios")
                        .HasForeignKey("Id_vehiculo_proveedor", "Id_vehiculo", "Id_proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lugar");

                    b.Navigation("Poliza_Cliente");

                    b.Navigation("Trabajador");

                    b.Navigation("Vehiculo_Proveedor");
                });

            modelBuilder.Entity("backend.Domain.Entities.Poliza_Cliente", b =>
                {
                    b.HasOne("backend.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Poliza_Clientes")
                        .HasForeignKey("Id_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Poliza", "Poliza")
                        .WithMany("Poliza_Clientes")
                        .HasForeignKey("Id_poliza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Poliza");
                });

            modelBuilder.Entity("backend.Domain.Entities.Servicio_Orden", b =>
                {
                    b.HasOne("backend.Domain.Entities.Orden_De_Servicio", "Orden_De_Servicio")
                        .WithMany("Servicio_Ordenes")
                        .HasForeignKey("Id_orden_de_servicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Servicio", "Servicio")
                        .WithMany("Servicio_Ordenes")
                        .HasForeignKey("Id_servicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden_De_Servicio");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("backend.Domain.Entities.Telefono", b =>
                {
                    b.HasOne("backend.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Telefonos")
                        .HasForeignKey("Id_cliente");

                    b.HasOne("backend.Domain.Entities.Conductor", "Conductor")
                        .WithMany("Telefonos")
                        .HasForeignKey("Id_conductor");

                    b.HasOne("backend.Domain.Entities.Trabajador", "Trabajador")
                        .WithMany("Telefonos")
                        .HasForeignKey("Id_trabajador");

                    b.Navigation("Cliente");

                    b.Navigation("Conductor");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("backend.Domain.Entities.Trabajador_Departamento", b =>
                {
                    b.HasOne("backend.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Trabajador_Departamentos")
                        .HasForeignKey("Id_departamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Trabajador", "Trabajador")
                        .WithMany("Trabajador_Departamentos")
                        .HasForeignKey("Id_trabajador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("backend.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("backend.Domain.Entities.Conductor", "Conductor")
                        .WithOne()
                        .HasForeignKey("backend.Domain.Entities.Usuario", "Id_conductor");

                    b.HasOne("backend.Domain.Entities.Proveedor", "Proveedor")
                        .WithOne()
                        .HasForeignKey("backend.Domain.Entities.Usuario", "Id_proveedor");

                    b.HasOne("backend.Domain.Entities.Trabajador", "Trabajador")
                        .WithOne()
                        .HasForeignKey("backend.Domain.Entities.Usuario", "Id_trabajador");

                    b.Navigation("Conductor");

                    b.Navigation("Proveedor");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("backend.Domain.Entities.Usuario_Rol", b =>
                {
                    b.HasOne("backend.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuario_Roles")
                        .HasForeignKey("Id_rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Usuario_Roles")
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Domain.Entities.Vehiculo", b =>
                {
                    b.HasOne("backend.Domain.Entities.Tipo_Vehiculo", "Tipo_Vehiculo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("Id_tipo_vehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo_Vehiculo");
                });

            modelBuilder.Entity("backend.Domain.Entities.Vehiculo_Proveedor", b =>
                {
                    b.HasOne("backend.Domain.Entities.Conductor", "Conductor")
                        .WithMany("Vehiculo_Proveedores")
                        .HasForeignKey("Id_conductor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Vehiculo_Proveedores")
                        .HasForeignKey("Id_proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Vehiculo_Proveedores")
                        .HasForeignKey("Id_vehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Proveedor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("backend.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Poliza_Clientes");

                    b.Navigation("Telefonos");
                });

            modelBuilder.Entity("backend.Domain.Entities.Conductor", b =>
                {
                    b.Navigation("Telefonos");

                    b.Navigation("Vehiculo_Proveedores");
                });

            modelBuilder.Entity("backend.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Trabajador_Departamentos");
                });

            modelBuilder.Entity("backend.Domain.Entities.Estado", b =>
                {
                    b.Navigation("Estado_Ordenes");
                });

            modelBuilder.Entity("backend.Domain.Entities.Lugar", b =>
                {
                    b.Navigation("LugaresHijos");

                    b.Navigation("Orden_De_Servicios");
                });

            modelBuilder.Entity("backend.Domain.Entities.Orden_De_Servicio", b =>
                {
                    b.Navigation("Estado_Ordenes");

                    b.Navigation("Servicio_Ordenes");
                });

            modelBuilder.Entity("backend.Domain.Entities.Poliza", b =>
                {
                    b.Navigation("Poliza_Clientes");
                });

            modelBuilder.Entity("backend.Domain.Entities.Poliza_Cliente", b =>
                {
                    b.Navigation("Orden_De_Servicios");
                });

            modelBuilder.Entity("backend.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Vehiculo_Proveedores");
                });

            modelBuilder.Entity("backend.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuario_Roles");
                });

            modelBuilder.Entity("backend.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("Servicio_Ordenes");
                });

            modelBuilder.Entity("backend.Domain.Entities.Tipo_Vehiculo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("backend.Domain.Entities.Trabajador", b =>
                {
                    b.Navigation("Orden_De_Servicios");

                    b.Navigation("Telefonos");

                    b.Navigation("Trabajador_Departamentos");
                });

            modelBuilder.Entity("backend.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Usuario_Roles");
                });

            modelBuilder.Entity("backend.Domain.Entities.Vehiculo", b =>
                {
                    b.Navigation("Vehiculo_Proveedores");
                });

            modelBuilder.Entity("backend.Domain.Entities.Vehiculo_Proveedor", b =>
                {
                    b.Navigation("Orden_De_Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
