global using API_GruasUCAB.Users.Infrastructure.DTOs.AdministratorQueries;
global using API_GruasUCAB.Users.Infrastructure.DTOs.ProviderQueries;
global using API_GruasUCAB.Users.Infrastructure.DTOs.DriverQueries;
global using API_GruasUCAB.Users.Infrastructure.DTOs.WorkerQueries;
global using API_GruasUCAB.Users.Infrastructure.DTOs.RecordUserData;
global using API_GruasUCAB.Users.Infrastructure.DTOs.UpdateUser;
global using API_GruasUCAB.Core.Infrastructure.DTOs;
global using System.ComponentModel.DataAnnotations;
global using System.Text.Json.Serialization;