global using API_GruasUCAB.ServiceOrder.Application.Queries.GetServiceOrdersByStatus;
global using API_GruasUCAB.ServiceOrder.Application.Queries.GetServiceOrderById;
global using API_GruasUCAB.ServiceOrder.Application.Queries.GetAllServiceOrders;
global using API_GruasUCAB.ServiceOrder.Application.Queries.GetOrdersByDriverId;
global using API_GruasUCAB.ServiceOrder.Application.Queries.GetOrdersByVehicleId;
global using API_GruasUCAB.ServiceOrder.Application.Queries.GetOrdersByOperatorId;
global using API_GruasUCAB.ServiceOrder.Application.Queries.GetOrdersBySupplierId;
global using API_GruasUCAB.ServiceOrder.Application.Queries.GetOrdersByClientId;