global using API_GruasUCAB.ServiceFee.Application.Queries.GetServiceFeeByName;
global using API_GruasUCAB.ServiceFee.Application.Queries.GetServiceFeeById;
global using API_GruasUCAB.ServiceFee.Application.Queries.GetAllServiceFees;